### PR TITLE
Optional method

### LINKED ISSUE #4: Optional HTTP verb
**Describe the bug**
Trying to run a request without a HTTP verb results in an error.

**To Reproduce**
1. This script file content `http://pokeapi.co/api/v2`
2. See error
```
Error: Failed parsing file: "tests/sample.http"

Caused by:
     --> 1:1
      |
    1 | http://pokeapi.co/api/v2
      | ^---
      |
      = expected file
```

**Expected behavior**
`GET` should be the fallback or default verb and thus a GET request with the provided url should be issued.

**Additional context**
I'm already working on a PR to achieve this: https://github.com/lcptrs/dothttp/tree/optional-method

### PR DESCRIPTION
**Pull request by lcptrs**
This makes the HTTP verb / method optional like in Jetbrains HTTPClient.
closes #4

### CODE REVIEW

File: tests/simple.rs [hunk 1]
```diff
@@ -26,6 +26,10 @@ fn simple_get() {
         "GET http://localhost:{port}/simple_get/{{{{id}}}}",
         port = server.port()
     ));
+    let script_file_without_method = create_file(&format!(
```
Comment (alisa101rs) [inline tests/simple.rs]: In order to keep this test truly `simple_get` let's leave only 1 get request inside the body. 

To test the fallback on `GET` method, we can either:
1. remove explicit `GET` method in `simple_get` test 
```rust
    let script_file = create_file(&format!(
        "http://localhost:{port}/simple_get/{{{{id}}}}",
        port = server.port()
    ));
```
2. Add this new test in the `multi.rs` file
    
Personally I think taking easiest option 1 should be fine

**Review by alisa101rs — CHANGES_REQUESTED** [review]
Thank you, I left a minor nitpick comment regarding the test, everything else looks good!

File: tests/simple.rs (hunk 1 above)
Comment (lcptrs) [reply tests/simple.rs]: I agree on the nitpick. I'm not happy with the test and my change on it tbh. I've implemented your first approach as I think it's good enough for now.
My problem with this: I've played a bit around with the parsing and found for example that the parser is really strict about whitespaces compared to jetbrains http client. I'd like to have proper unit tests that focuses on the parsing alone to make it easier to cover mutliple test cases. I'll create a separate issue for this.
